import type { Service, Tenant, ChangeRequest } from "@/lib/db/schema";
import { systemPrompt, userPrompt } from "./prompts";

export type Artifacts = {
  dockerfile: string;
  ciWorkflow: string;
  helmValues: string;
  ciPipelineRef: string;
  summary: string;
};

/**
 * Generate the Dockerfile / CI / Helm values for a Service+ChangeRequest.
 *
 * AI_MODE=mock  — returns deterministic templates (used in MVP1 and tests).
 * AI_MODE=bedrock — calls Bedrock InvokeModel (MVP2; not implemented).
 */
export async function generateArtifacts(args: {
  service: Service;
  tenant: Tenant;
  changeRequest: ChangeRequest;
}): Promise<Artifacts> {
  const mode = process.env.AI_MODE ?? "mock";

  if (mode === "mock") {
    return mockArtifacts(args);
  }

  if (mode === "bedrock") {
    // TODO MVP2: @aws-sdk/client-bedrock-runtime invokeModel with the prompts from prompts.ts.
    // Keep the return type identical so call sites don't change.
    const _sys = systemPrompt();
    const _usr = userPrompt(args);
    throw new Error("AI_MODE=bedrock not implemented in MVP1");
  }

  throw new Error(`unknown AI_MODE: ${mode}`);
}

function mockArtifacts(args: {
  service: Service;
  tenant: Tenant;
  changeRequest: ChangeRequest;
}): Artifacts {
  const { service, tenant } = args;
  const serviceSlug = service.name.toLowerCase().replace(/[^a-z0-9-]/g, "-");

  const dockerfile = `# Generated by SSP AI agent (mock) — review before merge
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
RUN addgroup -S app && adduser -S app -G app
WORKDIR /app
COPY --from=build --chown=app:app /app /app
USER app
EXPOSE 8080
CMD ["node", "dist/index.js"]
`;

  const ciWorkflow = `# Generated by SSP AI agent (mock)
name: build-and-push

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ vars.ECR_PUSH_ROLE_ARN }}
          aws-region: \${{ vars.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
      - name: Build & push
        env:
          REGISTRY: \${{ steps.ecr.outputs.registry }}
          REPO: ${serviceSlug}
          TAG: \${{ github.sha }}
        run: |
          docker build -t "$REGISTRY/$REPO:$TAG" .
          docker push "$REGISTRY/$REPO:$TAG"
`;

  const helmValues = `# Generated by SSP AI agent (mock) for service ${service.name} (tenant ${tenant.domain})
image:
  repository: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/${serviceSlug}
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 8080

# Gateway API HTTPRoute — attaches to the shared internal/public ALB Gateway.
route:
  enabled: ${Boolean(service.subdomain)}
  host: "${service.subdomain ?? service.name}.${tenant.domain}.ssp.eaglesoftvn.com"
  vpnInternal: ${service.vpnInternal}
  tls: ${!service.vpnInternal}
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/ssp-tenant-${tenant.domain}"

tenant:
  id: "${tenant.id}"
  domain: "${tenant.domain}"
  department: "${tenant.department}"
  costCenter: "${tenant.department}-eng"
  product: "ssp-tenant-workload"
  environment: "shared-prod"

ssp:
  serviceId: "${service.id}"
  changeRequestId: "${args.changeRequest.id}"
  revisionId: "(filled at insert time)"
`;

  const summary = `Mock AI summary: generated Dockerfile (node:20-alpine, non-root), GitHub Actions workflow with OIDC-based ECR push, Helm values for tenant ${tenant.domain}/${service.name}. No code changes proposed in the application repo.`;

  return {
    dockerfile,
    ciWorkflow,
    helmValues,
    ciPipelineRef: `${service.gitRepo}/.github/workflows/build.yml`,
    summary,
  };
}
