import type { Service, Tenant, ChangeRequest } from "@/lib/db/schema";
import {
  BedrockRuntimeClient,
  InvokeModelCommand,
} from "@aws-sdk/client-bedrock-runtime";
import { systemPrompt, userPrompt } from "./prompts";

export type Artifacts = {
  dockerfile: string;
  ciWorkflow: string;
  helmValues: string;
  ciPipelineRef: string;
  summary: string;
};

/**
 * Generate the Dockerfile / CI / Helm values for a Service+ChangeRequest.
 *
 * AI_MODE=mock    — deterministic templates (used in CI / offline dev).
 * AI_MODE=bedrock — Claude on Bedrock with prompt caching on the system prompt.
 */
export async function generateArtifacts(args: {
  service: Service;
  tenant: Tenant;
  changeRequest: ChangeRequest;
}): Promise<Artifacts> {
  const mode = process.env.AI_MODE ?? "mock";

  if (mode === "bedrock") {
    return bedrockArtifacts(args);
  }
  if (mode === "mock") {
    return mockArtifacts(args);
  }
  throw new Error(`unknown AI_MODE: ${mode}`);
}

// ---------------------------------------------------------------------------
// Bedrock — real Claude inference
// ---------------------------------------------------------------------------

let cachedClient: BedrockRuntimeClient | null = null;
function client(): BedrockRuntimeClient {
  if (!cachedClient) {
    cachedClient = new BedrockRuntimeClient({
      region: process.env.BEDROCK_REGION ?? "eu-west-1",
    });
  }
  return cachedClient;
}

async function bedrockArtifacts(args: {
  service: Service;
  tenant: Tenant;
  changeRequest: ChangeRequest;
}): Promise<Artifacts> {
  const modelId =
    process.env.BEDROCK_MODEL_ID ?? "eu.anthropic.claude-sonnet-4-6";

  const sys = systemPrompt();
  const usr = userPrompt(args);

  const body = {
    anthropic_version: "bedrock-2023-05-31",
    max_tokens: 4096,
    // Prompt caching on the system prompt — same prompt across every Service/CR run, so
    // we only pay full-token cost on the first invocation per ~5min window.
    system: [
      {
        type: "text",
        text: sys,
        cache_control: { type: "ephemeral" },
      },
    ],
    messages: [
      {
        role: "user",
        content: [{ type: "text", text: usr }],
      },
    ],
  };

  const cmd = new InvokeModelCommand({
    modelId,
    contentType: "application/json",
    accept: "application/json",
    body: JSON.stringify(body),
  });

  const start = Date.now();
  const res = await client().send(cmd);
  const elapsed = Date.now() - start;

  const decoded = new TextDecoder().decode(res.body);
  const parsed = JSON.parse(decoded) as {
    content: Array<{ type: string; text?: string }>;
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
      cache_read_input_tokens?: number;
    };
  };

  const text = parsed.content
    .filter((b) => b.type === "text")
    .map((b) => b.text ?? "")
    .join("");

  const extracted = extractArtifacts(text);

  console.log(
    `bedrock ok model=${modelId} ms=${elapsed} tok_in=${parsed.usage?.input_tokens ?? "?"} tok_out=${parsed.usage?.output_tokens ?? "?"} cache_read=${parsed.usage?.cache_read_input_tokens ?? 0}`,
  );

  return {
    dockerfile: extracted.dockerfile,
    ciWorkflow: extracted.ci_workflow,
    helmValues: extracted.helm_values,
    ciPipelineRef: `${args.service.gitRepo}/.github/workflows/build.yml`,
    summary: extracted.summary,
  };
}

/**
 * Parse the model's response. The system prompt asks Claude to wrap each artifact in a
 * fenced code block with a known fence tag (dockerfile / ci / helm). The summary is the
 * prose before the first fence.
 */
function extractArtifacts(text: string): {
  dockerfile: string;
  ci_workflow: string;
  helm_values: string;
  summary: string;
} {
  const block = (tag: string): string => {
    const re = new RegExp("```" + tag + "\\s*\\n([\\s\\S]*?)\\n```", "i");
    return text.match(re)?.[1]?.trim() ?? "";
  };

  const firstFenceIdx = text.indexOf("```");
  const summary =
    firstFenceIdx > 0 ? text.slice(0, firstFenceIdx).trim() : "(no summary)";

  return {
    dockerfile: block("dockerfile") || block("Dockerfile"),
    ci_workflow: block("ci") || block("yaml") || block("yml"),
    helm_values: block("helm") || block("values"),
    summary,
  };
}

// ---------------------------------------------------------------------------
// Mock — deterministic templates for offline dev / CI
// ---------------------------------------------------------------------------

function mockArtifacts(args: {
  service: Service;
  tenant: Tenant;
  changeRequest: ChangeRequest;
}): Artifacts {
  const { service, tenant } = args;
  const serviceSlug = service.name.toLowerCase().replace(/[^a-z0-9-]/g, "-");

  const dockerfile = `# Generated by SSP AI agent (mock)
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
RUN addgroup -S app && adduser -S app -G app
WORKDIR /app
COPY --from=build --chown=app:app /app /app
USER app
EXPOSE 8080
CMD ["node", "dist/index.js"]
`;

  const ciWorkflow = `name: build-and-push

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ vars.ECR_PUSH_ROLE_ARN }}
          aws-region: \${{ vars.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
      - name: Build & push
        env:
          REGISTRY: \${{ steps.ecr.outputs.registry }}
          REPO: ${serviceSlug}
          TAG: \${{ github.sha }}
        run: |
          docker build -t "$REGISTRY/$REPO:$TAG" .
          docker push "$REGISTRY/$REPO:$TAG"
`;

  const helmValues = `image:
  repository: 195748744911.dkr.ecr.eu-west-1.amazonaws.com/${serviceSlug}
  tag: latest
service:
  port: 8080
route:
  enabled: ${Boolean(service.subdomain)}
  host: "${service.subdomain ?? service.name}.${tenant.domain}.ssp.mightybee.dev"
  vpnInternal: ${service.vpnInternal}
  tls: ${!service.vpnInternal}
tenant:
  id: "${tenant.id}"
  domain: "${tenant.domain}"
  department: "${tenant.department}"
ssp:
  serviceId: "${service.id}"
  changeRequestId: "${args.changeRequest.id}"
`;

  return {
    dockerfile,
    ciWorkflow,
    helmValues,
    ciPipelineRef: `${service.gitRepo}/.github/workflows/build.yml`,
    summary: `Mock AI summary: scaffolded Dockerfile + GitHub Actions OIDC ECR push + Helm values for ${tenant.domain}/${service.name}.`,
  };
}
