-- Generated by hand to match src/lib/db/schema.ts. After first install run
--   npm run db:generate
-- to regenerate; CI fails on drift.

CREATE TYPE "public"."service_status" AS ENUM (
  'na', 'aiReview', 'platformReview', 'provisioning', 'working', 'rejected'
);

CREATE TYPE "public"."change_request_status" AS ENUM (
  'submitted', 'aiReviewing', 'needsChanges', 'platformReviewing',
  'approved', 'rejected', 'merged', 'applied'
);

CREATE TYPE "public"."user_tenant_role" AS ENUM ('admin');

CREATE TABLE IF NOT EXISTS "tenants" (
  "id" text PRIMARY KEY,
  "domain" text NOT NULL,
  "tags" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "department" text NOT NULL,
  "head_of_department" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "tenants_domain_uq" ON "tenants" ("domain");

CREATE TABLE IF NOT EXISTS "users" (
  "id" text PRIMARY KEY,
  "cognito_sub" text NOT NULL,
  "email" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_cognito_sub_uq" ON "users" ("cognito_sub");
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_uq" ON "users" ("email");

CREATE TABLE IF NOT EXISTS "user_tenants" (
  "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "tenant_id" text NOT NULL REFERENCES "tenants"("id") ON DELETE CASCADE,
  "role" "user_tenant_role" NOT NULL DEFAULT 'admin',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "tenant_id")
);
CREATE INDEX IF NOT EXISTS "user_tenants_tenant_idx" ON "user_tenants" ("tenant_id");

CREATE TABLE IF NOT EXISTS "services" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL REFERENCES "tenants"("id") ON DELETE RESTRICT,
  "name" text NOT NULL,
  "subdomain" text,
  "vpn_internal" boolean NOT NULL DEFAULT true,
  "git_repo" text NOT NULL,
  "description" text NOT NULL,
  "current_status" "service_status" NOT NULL DEFAULT 'na',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz
);
CREATE INDEX IF NOT EXISTS "services_tenant_idx" ON "services" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "services_tenant_subdomain_uq"
  ON "services" ("tenant_id", "subdomain")
  WHERE "subdomain" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "change_requests" (
  "id" text PRIMARY KEY,
  "service_id" text NOT NULL REFERENCES "services"("id") ON DELETE CASCADE,
  "requested_by" text NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "status" "change_request_status" NOT NULL DEFAULT 'submitted',
  "summary" text NOT NULL,
  "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "change_requests_service_idx" ON "change_requests" ("service_id");
CREATE INDEX IF NOT EXISTS "change_requests_status_idx" ON "change_requests" ("status");

CREATE TABLE IF NOT EXISTS "service_revisions" (
  "id" text PRIMARY KEY,
  "change_request_id" text NOT NULL REFERENCES "change_requests"("id") ON DELETE CASCADE,
  "service_id" text NOT NULL REFERENCES "services"("id") ON DELETE CASCADE,
  "service_status" "service_status" NOT NULL,
  "cr_status" "change_request_status" NOT NULL,
  "ci_pipeline_ref" text,
  "dockerfile_snapshot" text,
  "cd_manifest_ref" text,
  "ai_summary" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "service_revisions_service_idx" ON "service_revisions" ("service_id");
CREATE INDEX IF NOT EXISTS "service_revisions_cr_idx" ON "service_revisions" ("change_request_id");

-- Enforce immutability of tenant.domain.
CREATE OR REPLACE FUNCTION reject_tenant_domain_update() RETURNS trigger AS $$
BEGIN
  IF NEW.domain IS DISTINCT FROM OLD.domain THEN
    RAISE EXCEPTION 'tenants.domain is immutable';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tenants_domain_immutable ON "tenants";
CREATE TRIGGER tenants_domain_immutable
  BEFORE UPDATE ON "tenants"
  FOR EACH ROW
  EXECUTE FUNCTION reject_tenant_domain_update();
