import type { Service, Tenant, ChangeRequest } from "@/lib/db/schema";
import type { Artifacts } from "@/lib/ai/agent";

export type FleetPr = {
  url: string;
  branch: string;
};

/**
 * Open a PR against the fleet-managers repo with the artifacts produced by the AI agent.
 *
 * MVP1: logs the PR plan to stdout and returns a fake URL. The real implementation
 * uses Octokit + a GitHub App; the call site does not change.
 */
export async function openFleetPr(args: {
  tenant: Tenant;
  service: Service;
  changeRequest: ChangeRequest;
  artifacts: Artifacts;
}): Promise<FleetPr> {
  const branch = `ssp/${args.tenant.domain}/${args.service.name}/cr-${args.changeRequest.id.slice(-6).toLowerCase()}`;
  const owner = process.env.FLEET_REPO_OWNER ?? "ORG";
  const repo = process.env.FLEET_REPO_NAME ?? "fleet-managers";

  if (!process.env.GITHUB_TOKEN || process.env.GITHUB_TOKEN.startsWith("ghp_REPLACE")) {
    const body = renderPrBody(args);
    console.log("--- SSP would open this PR ---");
    console.log(`repo:   ${owner}/${repo}`);
    console.log(`branch: ${branch}`);
    console.log("---");
    console.log(body);
    console.log("--- end PR body ---");
    return {
      url: `https://github.com/${owner}/${repo}/pull/MOCK-${args.changeRequest.id.slice(-6)}`,
      branch,
    };
  }

  // TODO MVP2: Octokit calls — create branch, commit files (tenants/<domain>/services/<svc>/values.yaml,
  // optionally the AI-generated Dockerfile + CI workflow into a separate PR against the *application* repo),
  // open PR with renderPrBody as body.
  throw new Error("real GitHub PR not implemented in MVP1");
}

function renderPrBody(args: {
  tenant: Tenant;
  service: Service;
  changeRequest: ChangeRequest;
  artifacts: Artifacts;
}) {
  return `## SSP change request

**Tenant:** ${args.tenant.domain} (${args.tenant.department})
**Service:** ${args.service.name}
**Change request:** ${args.changeRequest.id}
**Requested by:** ${args.changeRequest.requestedBy}

> ${args.changeRequest.summary}

### Files in this PR

- \`tenants/${args.tenant.domain}/services/${args.service.name}/values.yaml\`

### AI-generated artifacts (separate PR against the application repo)

- \`Dockerfile\`
- \`.github/workflows/build.yml\`

### AI summary

${args.artifacts.summary}

---

Auto-generated by the SSP portal. A platform engineer must review before merge.
`;
}
