import type { Service, Tenant, ChangeRequest } from "@/lib/db/schema";
import type { Artifacts } from "@/lib/ai/agent";
import { Octokit } from "@octokit/rest";

export type FleetPr = {
  url: string;
  number: number;
  branch: string;
};

/**
 * Open a PR against the fleet-managers repo with the artifacts produced by the AI agent.
 *
 * Files added/updated per CR (one atomic commit, one branch, one PR):
 *   - tenants/<tenant.domain>/apps/<service.name>/values.yaml      (Helm values)
 *   - tenants/<tenant.domain>/apps/<service.name>/Dockerfile       (frozen snapshot)
 *   - tenants/<tenant.domain>/apps/<service.name>/build.yml        (CI workflow)
 *   - tenants/<tenant.domain>/apps/<service.name>/application.yaml (ArgoCD Application)
 *
 * Without GITHUB_TOKEN: logs the PR body to stdout and returns a mock URL (dev fallback).
 */
export async function openFleetPr(args: {
  tenant: Tenant;
  service: Service;
  changeRequest: ChangeRequest;
  artifacts: Artifacts;
}): Promise<FleetPr> {
  const token = process.env.GITHUB_TOKEN ?? "";
  const owner = process.env.FLEET_REPO_OWNER ?? "nguyenhoangnam123";
  const repo = process.env.FLEET_REPO_NAME ?? "alice-ssp";
  const baseBranch = process.env.FLEET_REPO_BASE_BRANCH ?? "main";

  const branch = `ssp/${args.tenant.domain}/${args.service.name}/cr-${args.changeRequest.id.slice(-8).toLowerCase()}`;
  const body = renderPrBody(args);

  if (!token || token.startsWith("ghp_REPLACE")) {
    console.log("[github/pr] no token — logging PR plan instead");
    console.log(`repo:   ${owner}/${repo}`);
    console.log(`branch: ${branch}`);
    console.log("---");
    console.log(body);
    console.log("---");
    return {
      url: `https://github.com/${owner}/${repo}/pull/MOCK-${args.changeRequest.id.slice(-6)}`,
      number: 0,
      branch,
    };
  }

  const gh = new Octokit({ auth: token });

  const baseRef = await gh.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = baseRef.data.object.sha;

  try {
    await gh.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branch}`,
      sha: baseSha,
    });
  } catch {
    await gh.git.updateRef({
      owner,
      repo,
      ref: `heads/${branch}`,
      sha: baseSha,
      force: true,
    });
  }

  const baseDir = `fleet-managers/tenants/${args.tenant.domain}/apps/${args.service.name}`;
  const files: Array<{ path: string; content: string }> = [
    { path: `${baseDir}/values.yaml`, content: args.artifacts.helmValues },
    { path: `${baseDir}/Dockerfile`, content: args.artifacts.dockerfile },
    { path: `${baseDir}/build.yml`, content: args.artifacts.ciWorkflow },
    { path: `${baseDir}/application.yaml`, content: args.artifacts.argocdApp },
  ];

  const tree = await gh.git.createTree({
    owner,
    repo,
    base_tree: baseSha,
    tree: files.map((f) => ({
      path: f.path,
      mode: "100644",
      type: "blob",
      content: f.content,
    })),
  });

  const commit = await gh.git.createCommit({
    owner,
    repo,
    message: `ssp: ${args.tenant.domain}/${args.service.name} — ${args.changeRequest.summary}\n\nChange request: ${args.changeRequest.id}\nSummary: ${args.changeRequest.summary}\n\nGenerated by the SSP portal AI agent.`,
    tree: tree.data.sha,
    parents: [baseSha],
  });

  await gh.git.updateRef({
    owner,
    repo,
    ref: `heads/${branch}`,
    sha: commit.data.sha,
  });

  const pr = await gh.pulls.create({
    owner,
    repo,
    head: branch,
    base: baseBranch,
    title: `ssp: ${args.tenant.domain}/${args.service.name} — ${args.changeRequest.summary}`,
    body,
  });

  return {
    url: pr.data.html_url,
    number: pr.data.number,
    branch,
  };
}

function renderPrBody(args: {
  tenant: Tenant;
  service: Service;
  changeRequest: ChangeRequest;
  artifacts: Artifacts;
}): string {
  return `## SSP change request

**Tenant:** ${args.tenant.domain} (${args.tenant.department})
**Service:** ${args.service.name}
**Change request:** \`${args.changeRequest.id}\`
**Requested by:** ${args.changeRequest.requestedBy}

> ${args.changeRequest.summary}

### Files in this PR

- \`fleet-managers/tenants/${args.tenant.domain}/apps/${args.service.name}/values.yaml\`
- \`fleet-managers/tenants/${args.tenant.domain}/apps/${args.service.name}/Dockerfile\` *(frozen snapshot for review)*
- \`fleet-managers/tenants/${args.tenant.domain}/apps/${args.service.name}/build.yml\`
- \`fleet-managers/tenants/${args.tenant.domain}/apps/${args.service.name}/application.yaml\` *(ArgoCD Application — app-of-apps for the tenant)*

### AI agent output

${args.artifacts.summary}

---

Auto-generated by the SSP portal. A platform engineer must review and merge.
`;
}
