{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ .secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .target.name }}
    creationPolicy: Owner
    {{- with .target.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
