tenant:
  id: cbdbfcd6373448318d82ddc58d
  domain: alice
  department: platform

ssp:
  serviceId: 01KT4VQ06937KK4JNTCTJA20C8
  changeRequestId: 01KT4Y9W9Z9PTF3YXQAK4003FK

replicaCount: 2

image:
  repository: 195748744911.dkr.ecr.eu-west-1.amazonaws.com/ssp-portal
  tag: 8de218fd12a8eb54fc3d344e9a42dc9e741dc3f2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  - name: PORT
    value: "8080"

route:
  enabled: true
  host: api.ssp.mightybee.dev
  vpnInternal: false
  tls:
    enabled: true