tenant:
  id: cbdbfcd6373448318d82ddc58d
  domain: alice
  department: platform

ssp:
  serviceId: 01KT4VQ06937KK4JNTCTJA20C8
  changeRequestId: 01KT4ZZ5JGEHH6BS8MX8D9EJWD

replicaCount: 2

image:
  repository: docker.io/library/nginx
  tag: alpine
  pullPolicy: IfNotPresent

containerPort: 80

service:
  port: 80
  type: ClusterIP

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi

route:
  enabled: true
  host: api.ssp.mightybee.dev
  vpnInternal: false
  tls:
    enabled: true
    termination: edge

securityContext:
  runAsUser: 10001
  runAsNonRoot: true
  allowPrivilegeEscalation: false

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 5