apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenhoangnam123/alice-ssp.git
    targetRevision: main
    path: fleet-managers/helm/app
    helm:
      valueFiles:
        - "../../tenants/alice/apps/api-service/values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-alice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true