apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alice-fuzz-ok
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenhoangnam123/alice-ssp.git
    targetRevision: main
    path: fleet-managers/helm/app
    helm:
      valueFiles:
        - "../../tenants/alice/apps/fuzz-ok/values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-alice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true