tenant:
  id: cbdbfcd6373448318d82ddc58d
  domain: alice
  department: platform

ssp:
  serviceId: 01KT78ZPKE5JFAF17NJ5D9BJMY
  changeRequestId: 01KT8Z3A450C8TXKWGMHSQM9P9

replicaCount: 1

image:
  repository: 339713072162.dkr.ecr.us-east-1.amazonaws.com/chat
  tag: "${{ github.sha }}"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 256m
    memory: 2Gi
  limits:
    cpu: 512m
    memory: 2Gi

route:
  enabled: true
  host: chat.ssp.mightybee.dev
  vpnInternal: false
  tls:
    enabled: true
    secretName: chat-tls

serviceAccount:
  create: true
  name: chat

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL